src/Entity/Jury.php
<?php

namespace App\Entity;

use App\Repository\JuryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JuryRepository::class)]
class Jury
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fonction = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $organisation = null;


    #[ORM\OneToOne(targetEntity: User::class, inversedBy: 'jury', cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false, unique: true, onDelete: "CASCADE")]
    private ?User $user = null;

    /**
     * @var Collection<int, Recrutement>
     */
    #[ORM\ManyToMany(targetEntity: Recrutement::class)]
    #[ORM\JoinTable(name: 'jury_recrutement')]
    private Collection $recrutements;

    /**
     * @var Collection<int, Formation>
     */
    #[ORM\ManyToMany(targetEntity: Formation::class)]
    #[ORM\JoinTable(name: 'jury_formation')]
    private Collection $formations;

    /**
     * @var Collection<int, Vae>
     */
    #[ORM\ManyToMany(targetEntity: Vae::class)]
    #[ORM\JoinTable(name: 'jury_vae')]
    private Collection $vaes;

    /**
     * @var Collection<int, JuryDate>
     */
    #[ORM\OneToMany(targetEntity: JuryDate::class, mappedBy: 'jury', orphanRemoval: true)]
    private Collection $juryDates;

    #[ORM\ManyToOne(inversedBy: 'jury')]
    private ?Centre $centre = null;

    public function __construct()
    {
        $this->recrutements = new ArrayCollection();
        $this->formations = new ArrayCollection();
        $this->vaes = new ArrayCollection();
        $this->juryDates = new ArrayCollection();
    }

    /**
     * @return Collection<int, Recrutement>
     */
    public function getRecrutements(): Collection
    {
        return $this->recrutements;
    }

    public function addRecrutement(Recrutement $recrutement): static
    {
        if (!$this->recrutements->contains($recrutement)) {
            $this->recrutements->add($recrutement);
        }

        return $this;
    }

    public function removeRecrutement(Recrutement $recrutement): static
    {
        $this->recrutements->removeElement($recrutement);

        return $this;
    }

    /**
     * @return Collection<int, Formation>
     */
    public function getFormations(): Collection
    {
        return $this->formations;
    }

    public function addFormation(Formation $formation): static
    {
        if (!$this->formations->contains($formation)) {
            $this->formations->add($formation);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): static
    {
        $this->formations->removeElement($formation);

        return $this;
    }

    /**
     * @return Collection<int, Vae>
     */
    public function getVaes(): Collection
    {
        return $this->vaes;
    }

    public function addVae(Vae $vae): static
    {
        if (!$this->vaes->contains($vae)) {
            $this->vaes->add($vae);
        }

        return $this;
    }

    public function removeVae(Vae $vae): static
    {
        $this->vaes->removeElement($vae);

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): string
    {
        return trim(sprintf('%s %s', $this->prenom ?? '', $this->nom ?? ''));
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getFonction(): ?string
    {
        return $this->fonction;
    }

    public function setFonction(?string $fonction): static
    {
        $this->fonction = $fonction;

        return $this;
    }

    public function getOrganisation(): ?string
    {
        return $this->organisation;
    }

    public function setOrganisation(?string $organisation): static
    {
        $this->organisation = $organisation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getNomComplet(): string
    {
        return trim(sprintf('%s %s', $this->prenom, $this->nom));
    }

    public function getCentre(): ?Centre
    {
        return $this->centre;
    }

    public function setCentre(?Centre $centre): static
    {
        $this->centre = $centre;

        return $this;
    }

    /**
 * @return Collection<int, JuryDate>
 */
public function getJuryDates(): Collection
{
    return $this->juryDates;
}

public function addJuryDate(JuryDate $juryDate): static
{
    if (!$this->juryDates->contains($juryDate)) {
        $this->juryDates->add($juryDate);
        $juryDate->setJury($this);
    }

    return $this;
}

public function removeJuryDate(JuryDate $juryDate): static
{
    if ($this->juryDates->removeElement($juryDate)) {
        // set the owning side to null (unless already changed)
        if ($juryDate->getJury() === $this) {
            $juryDate->setJury(null);
        }
    }

    return $this;
}
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 180)]
    #[Assert\NotBlank(message: 'L\'email est obligatoire')]
    #[Assert\Email(message: 'Veuillez entrer un email valide')]
    #[Assert\Length(
        max: 180,
        maxMessage: 'L\'email ne peut pas dépasser {{ limit }} caractères'
    )]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    /**
     * @var string|null The plain password (not persisted)
     */
    #[Assert\NotBlank(message: 'Le mot de passe est obligatoire', groups: ['registration'])]
    #[Assert\Length(
        min: 6,
        max: 50,
        minMessage: 'Le mot de passe doit contenir au moins {{ limit }} caractères',
        maxMessage: 'Le mot de passe ne peut pas dépasser {{ limit }} caractères',
        groups: ['registration']
    )]
    private ?string $plainPassword = null;





    /**
     * @var Collection<int, Recrutement>
     */
    #[ORM\OneToMany(targetEntity: Recrutement::class, mappedBy: 'user')]
    private Collection $Recrutement;

    /**
     * @var Collection<int, Projet>
     */
    #[ORM\OneToMany(targetEntity: Projet::class, mappedBy: 'user')]
    private Collection $Projet;

    /**
     * @var Collection<int, Formation>
     */
    #[ORM\OneToMany(targetEntity: Formation::class, mappedBy: 'user')]
    private Collection $Formation;

    /**
     * @var Collection<int, Candidature>
     */
    #[ORM\OneToMany(targetEntity: Candidature::class, mappedBy: 'user')]
    private Collection $Candidature;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: Jury::class)]
    private ?Jury $jury = null;

    /**
     * @var Collection<int, EvaluationCandidature>
     */
    #[ORM\OneToMany(targetEntity: EvaluationCandidature::class, mappedBy: 'user')]
    private Collection $Evaluation;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?NiveauEtude $NiveauEtude = null;


#[ORM\ManyToOne(inversedBy: 'users')]
private ?CfaEtablissement $cfaEtablissement = null;

    /**
     * @var Collection<int, Diplome>
     */
    #[ORM\ManyToMany(targetEntity: Diplome::class, inversedBy: 'users')]
    private Collection $Diplome;

    public function __construct()
    {
        $this->Recrutement = new ArrayCollection();
        $this->Projet = new ArrayCollection();
        $this->Formation = new ArrayCollection();
        $this->Candidature = new ArrayCollection();
        $this->Evaluation = new ArrayCollection();
        $this->Diplome = new ArrayCollection();
        
        // Définir le rôle CANDIDAT par défaut
        $this->roles = ['ROLE_CANDIDAT'];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Ensure the session doesn't contain actual password hashes by CRC32C-hashing them, as supported since Symfony 7.3.
     */
    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0" . self::class . "\0password"] = hash('crc32c', $this->password);

        return $data;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }

    /**
     * @return Collection<int, Recrutement>
     */
    public function getRecrutement(): Collection
    {
        return $this->Recrutement;
    }

    public function addRecrutement(Recrutement $recrutement): static
    {
        if (!$this->Recrutement->contains($recrutement)) {
            $this->Recrutement->add($recrutement);
            $recrutement->setUser($this);
        }

        return $this;
    }

    public function removeRecrutement(Recrutement $recrutement): static
    {
        if ($this->Recrutement->removeElement($recrutement)) {
            // set the owning side to null (unless already changed)
            if ($recrutement->getUser() === $this) {
                $recrutement->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Projet>
     */
    public function getProjet(): Collection
    {
        return $this->Projet;
    }

    public function addProjet(Projet $projet): static
    {
        if (!$this->Projet->contains($projet)) {
            $this->Projet->add($projet);
            $projet->setUser($this);
        }

        return $this;
    }

    public function removeProjet(Projet $projet): static
    {
        if ($this->Projet->removeElement($projet)) {
            // set the owning side to null (unless already changed)
            if ($projet->getUser() === $this) {
                $projet->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Formation>
     */
    public function getFormation(): Collection
    {
        return $this->Formation;
    }

    public function addFormation(Formation $formation): static
    {
        if (!$this->Formation->contains($formation)) {
            $this->Formation->add($formation);
            $formation->setUser($this);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): static
    {
        if ($this->Formation->removeElement($formation)) {
            // set the owning side to null (unless already changed)
            if ($formation->getUser() === $this) {
                $formation->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidature(): Collection
    {
        return $this->Candidature;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->Candidature->contains($candidature)) {
            $this->Candidature->add($candidature);
            $candidature->setUser($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->Candidature->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getUser() === $this) {
                $candidature->setUser(null);
            }
        }

        return $this;
    }

    public function getJury(): ?Jury
    {
        return $this->jury;
    }

    public function setJury(?Jury $jury): static
    {
        // unset the owning side of the relation if necessary
        if ($jury === null && $this->jury !== null) {
            $this->jury->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($jury !== null && $jury->getUser() !== $this) {
            $jury->setUser($this);
        }

        $this->jury = $jury;
        return $this;
    }

    /**
     * @return Collection<int, EvaluationCandidature>
     */
    public function getEvaluation(): Collection
    {
        return $this->Evaluation;
    }

    public function addEvaluation(EvaluationCandidature $evaluation): static
    {
        if (!$this->Evaluation->contains($evaluation)) {
            $this->Evaluation->add($evaluation);
            $evaluation->setUser($this);
        }

        return $this;
    }

    public function removeEvaluation(EvaluationCandidature $evaluation): static
    {
        if ($this->Evaluation->removeElement($evaluation)) {
            // set the owning side to null (unless already changed)
            if ($evaluation->getUser() === $this) {
                $evaluation->setUser(null);
            }
        }

        return $this;
    }

    public function getNiveauEtude(): ?NiveauEtude
    {
        return $this->NiveauEtude;
    }

    public function setNiveauEtude(?NiveauEtude $NiveauEtude): static
    {
        $this->NiveauEtude = $NiveauEtude;

        return $this;
    }


    public function getCfaEtablissement(): ?CfaEtablissement
{
    return $this->cfaEtablissement;
}

public function setCfaEtablissement(?CfaEtablissement $cfaEtablissement): static
{

templates/print/printIns.html.twig
<!DOCTYPE html>
<html lang='fr'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>{{ recrutement.entreprise|upper }} - {{ recrutement.nom|upper }} - FICHE D'INSCRIPTION CANDIDAT</title>
    <style>
        @page{
            size: A4;
            margin: 0cm;
        }
        * {
            box-sizing: border-box;
        }
        .container {
            margin: 0.8cm;
        }
        section {
            padding: 0px 15px;
        }
        .row{
            display:flex;
            justify-content:flex-start;
            align-items:stretch;
            flex-wrap:nowrap;
            padding:1px;
        }
        .row_large{
            display: flex;
            flex-direction: row;
            flex-wrap: nowrap;
            justify-content: space-between;
            align-items: stretch;
            align-content: stretch;
        }
        .cell{
            min-height: 26px;
            flex-grow: 1;
            flex-basis: 100%;
            padding: 2px;
        }
        .title{
            text-align: center;
            font-weight: bold;
            font-size: 1.2em;
            margin-top: 20px;
        }
        .subtitle {
            padding: 5px;
            font-weight: bold;
            font-size: 1.1em;
            text-align: center;
            border: 1px solid black;
            margin: 10px 0 20px 0;
        }
        .subtitle2 {
            padding: 2px;
            font-style: italic;
            text-decoration: none;
        }
        .subtitle3 {
            text-align:center;
            text-decoration: none;
            margin-bottom: 20px;
            font-style: italic;
        }
        .stamp{
            width: 120px;
            height: 150px;
            float: right;
            margin: 10px auto;
            border: 1px solid #333;
        }
        .label{
            font-size: 1em;
        }
        .result{
            font-weight: bold;
            font-size: 1em;
        }
        @media (max-width: 768px){
            .row{
                flex-wrap: wrap;
            }
        }
        .footer {
            position: fixed;
            bottom: 10;
            width: 100%;
            text-align: center;
        }
        .footer img {
            display: block;
        }
    </style>
</head>
<body>
    <div class='container'>
        <section for='logo'>
            <img src='{{ image.entete }}' alt=''  style='width: 100%'>
        </section>
        <br>
        <section for='title'>
            <div class='row'>
                <div class='cell'>
                    <div class='title'> {{ recrutement.nom|upper }} </div>
                    <div class='subtitle'>FICHE D'INSCRIPTION CANDIDAT</div>
                    <div class='subtitle2'>N° d'enregistrement: <b>{{ candidature.numCandidature }}</b></div>
                    <div class='subtitle2'>DEMANDE D'INSCRIPTION À LA SESSION DE: 2025</div>
                   
                </div>
            </div>
        </section>
        <!-- Section photo du candidat -->
        <div style="float: right; width: 150px; margin: 10px 30px 10px 10px; text-align: center;">
            {% if image.photo is defined and image.photo is not empty %}
                <img src="{{ image.photo }}" alt="Photo du candidat" style="max-width: 100%; max-height: 180px; border: 1px solid #ddd; border-radius: 4px; padding: 3px;">
                
            {% else %}
                <div style="height: 180px; display: flex; align-items: center; justify-content: center; border: 1px dashed #999; background-color: #f9f9f9; color: #777; font-style: italic; padding: 10px; border-radius: 4px;">
                    Photo non disponible
                </div>
            {% endif %}
        </div>

        <section>
            <div class='row'>
                <div class='cell'>
                    <span class='label'>Nom & Prénoms :</span> <span class='result'>{{ candidature.nom|upper }}</span> &nbsp;&nbsp; <span class='result'>{{ candidature.prenom|upper }}</span>
                </div>
                {% if (candidature.nomJeuneFille is not null) %}
                <div class='cell'>
                    <span class='label'>Nom de jeune fille :</span> <span class='result'>{{ candidature.nomJeuneFille|upper }}</span>
                </div>
                {% endif %}
                <div class='cell'>
                    <span class='label'>Date & lieu de naissance :</span> <span class='result'>{{ candidature.dateNaissance|date('d/m/Y') }}</span> &nbsp;&nbsp;&nbsp; à &nbsp;&nbsp;&nbsp;<span class='result'>{{ candidature.lieuNaissance|upper }}</span>
                </div>
                <div class='cell'>
                    <span class='label'>Sexe :</span> <span class='result'>{{ candidature.sexe }}</span>
                </div>
                <div class='cell'>
                    <span class='label'>Contact :</span> <span class='result'> {{ candidature.contacts }} {{ candidature.contact2 ? " - " ~ candidature.contact2 : "" }}</span>
                </div>
                <div class='cell'>
                    <span class='label'>Adresse e-mail :</span> <span class='result'> {{ candidature.email }}</span>
                </div>
                <div class='cell'>
                    <span class='label'>Niveau d'étude :</span> <span class='result'>{{ candidature.niveauEtude ? candidature.niveauEtude.libelle : '' }}</span>
                </div>
                <div class='cell'>
                    <span class='label'>Métier :</span> <span class='result'>{{ candidature.metier ? candidature.metier.nom : '' }}</span>
                </div>
            </div>
        </section>
        <section class='footer'>
            <img src='https://api.qrcode.tec-it.com/API/QRCode?data={{ candidature.numCandidature }}&backcolor=ffffff&qzoned=2&download=0&filetype=PNG&margin=0&size=5' alt='QR Code'><br>
            <small> {{ "now"|date('Y') }} - {{ recrutement.entreprise|upper }}. Tous Droits Réservés</small>
        </section>
    </div>
</body>
</html>